version: 2
jobs:
  jest:
    working_directory: ~/lazysearch-js
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run: |
          npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths: node_modules
      - run: npm run-script test

workflows:
  version: 2
  test:
    jobs:
      - jest
